export const stackList = {
  전체: [
    "aws",
    "docker",
    "express",
    "figma",
    "firebase",
    "flutter",
    "go",
    "graphQL",
    "java",
    "javascript",
    "kotlin",
    "mongoDB",
    "mySQL",
    "next",
    "nest",
    "node",
    "php",
    "python",
    "react",
    "reactNative",
    "spring",
    "svelte",
    "swift",
    "typescript",
    "unity",
    "vue",
  ],
  프론트엔드: ["javascript", "typescript", "react", "vue", "svelte", "next"],
  백엔드: [
    "java",
    "spring",
    "node",
    "nest",
    "go",
    "kotlin",
    "express",
    "mySQL",
    "mongoDB",
    "python",
    "php",
    "graphQL",
    "firebase",
  ],
  기타: ["aws", "swift", "reactNative", "unity", "docker", "figma", "flutter"],
};
