interface StackType {
  [prop: string]: any;
}

export const stackList: StackType = {
  전체: [
    "Aws",
    "Docker",
    "Express",
    "Figma",
    "Firebase",
    "Flutter",
    "Go",
    "GraphQL",
    "Java",
    "JavaScript",
    "Kotlin",
    "MongoDB",
    "MySQL",
    "Next",
    "Nest",
    "Node",
    "Php",
    "Python",
    "React",
    "ReactNative",
    "Spring",
    "Svelte",
    "Swift",
    "Typescript",
    "Unity",
    "Vue",
  ],
  프론트엔드: ["JavaScript", "Typescript", "React", "Vue", "Svelte", "Next"],
  백엔드: [
    "Java",
    "Spring",
    "Node",
    "Nest",
    "Go",
    "Kotlin",
    "Express",
    "MySQL",
    "MongoDB",
    "Python",
    "Php",
    "GraphQL",
    "Firebase",
  ],
  기타: ["Aws", "Swift", "ReactNative", "Unity", "Docker", "Figma", "Flutter"],
};
